# SPDX-FileCopyrightText: 2023-2024 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

[versions]
aws = "2.41.25"
bouncycastle = "1.83"
flyway = "12.0.0"
fuel = "2.3.1"
hikaricp = "7.0.2"
httpclient = "4.5.14"
jackson = "2.21.0"
java = "25"
java-jwt = "4.5.0"
jdbi = "3.51.0"
jsoup = "1.22.1"
junit = "6.0.2"
kotlin = "2.3.10"
kotlin-logging = "3.0.5"
ktlint = "1.4.1"
ktlint-gradle = "14.0.1"
logback-access = "1.5.29"
logstash-logback = "8.1"
okhttp = "5.3.2"
owasp = "12.2.0"
playwright = "1.58.0"
postgresql = "42.7.9"
spring-boot = "4.0.2"
spring-dependency-management = "1.1.7"
tika = "3.2.3"
unbescape = "1.1.6.RELEASE"

[libraries]
aws-bom = { module = "software.amazon.awssdk:bom", version.ref = "aws" }
bouncycastle-bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
commons-jxpath = { module = "commons-jxpath:commons-jxpath", version = "1.4.0" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.20.0" }
eclipse-emf-ecore-xmi = { module = "org.eclipse.emf:org.eclipse.emf.ecore.xmi", version = "2.39.0" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
fuel = { module = "com.github.kittinunf.fuel:fuel", version.ref = "fuel" }
fuel-jackson = { module = "com.github.kittinunf.fuel:fuel-jackson", version.ref = "fuel" }
geotools-epsg-hsql = { module = "org.geotools:gt-epsg-hsql", version = "34.2" }
geotools-geopkg = { module = "org.geotools:gt-geopkg", version = "34.2" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclient" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }
jdbi-bom = { module = "org.jdbi:jdbi3-bom", version.ref = "jdbi" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
kotlin-logging = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "kotlin-logging" }
logback-access = { module = "ch.qos.logback:logback-access", version.ref = "logback-access" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
playwright = { module = "com.microsoft.playwright:playwright", version.ref = "playwright" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "2.5" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version = "3.51.1.0" }
tika-core = { module = "org.apache.tika:tika-core", version.ref = "tika" }
unbescape = { module = "org.unbescape:unbescape", version.ref = "unbescape" }

[plugins]
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
owasp = { id = "org.owasp.dependencycheck", version.ref = "owasp" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
